### ISSUE TITLE
IndexPage fails to compile

### ISSUE THREAD

**Issue by jamesdbruner** [alexislepresle/gatsby-shopify-theme#2]
I love the work you guys are doing! I ran into an error just trying to get the index page to compile when I cloned your repo down.

Component names need to be capitalized in React, or they won't work I did a little digging and you just need to change these two lines:

```javascript
const productList = ({data}) => {
```
and
```javascript
export default productList;
```

Should be 

```javascript
const ProductList = ({data}) => {
```

```javascript
export default ProductList;
```

Permalinks to those lines.
https://github.com/alexislepresle/gatsby-shopify-theme/blob/fce8708b73512431d5ce8039e706575ddf73c015/src/components/productList.js#L5
https://github.com/alexislepresle/gatsby-shopify-theme/blob/fce8708b73512431d5ce8039e706575ddf73c015/src/components/productList.js#L145

I can put in a PR if you'd like or you guys can handle it. /shrug

**Comment by alexislepresle** [comment]
Thank you, I just fixed the problem :)
