### ISSUE TITLE
Poor Google Page Speed Results

### ISSUE THREAD

**Issue by Chizzah** [alexislepresle/gatsby-shopify-theme#4]
Hi Alexis,

Hope you are doing well during this pandemic. I have been playing around with your theme/starter and I find it a joy to work with. Everything is perfect with the exception of one issue: Google Page Speed results

It seems like somewhere something is sending a doubled request and the JS bundle is unusually large. I have tried to remove things and analyzed with webpack bundle analyzer over the past month and a half but could not find the issue.

I thought asking you would be a good last resort.

**Comment by emiled** [comment]
+1 unfortunately in the same position, frustrated that I did not check the performance sooner, or did my due diligence with this repo. Will begin porting my work over to this alternative repo -> https://github.com/AlexanderProd/gatsby-shopify-starter

**Comment by Chizzah** [comment]
I found this in Luke's repository https://github.com/lukebennett88/gatsby-shopify-starter-opinionated.

Have you found a way to filter and sort products in https://github.com/AlexanderProd/gatsby-shopify-starter?

**Comment by alexislepresle** [comment]
Hello everyone, I'm improving the theme code, I'll try to see how to fix this problem :)

**Comment by Chizzah** [comment]
Hi Alexis,

That is great news. Looking forward to it. Also thank you for the great work.

**Comment by emiled** [comment]
Oh cool, i have managed to improve the performance substantially by auditing the dependencies in the `package.json.`

Current dependencies look like this:

`  "dependencies": {
    "bulma": "^0.7.5",
    "dotenv": "^8.2.0",
    "gatsby": "^2.24.9",
    "gatsby-image": "^2.4.13",
    "gatsby-plugin-google-analytics": "^2.3.13",
    "gatsby-plugin-layout": "^1.3.10",
    "gatsby-plugin-manifest": "^2.4.20",
    "gatsby-plugin-react-helmet": "^3.3.10",
    "gatsby-plugin-sass": "^2.3.12",
    "gatsby-plugin-sharp": "^2.6.21",
    "gatsby-source-filesystem": "^2.3.22",
    "gatsby-source-shopify": "^3.2.24",
    "gatsby-transformer-sharp": "^2.5.11",
    "node-sass": "^4.14.1",
    "prop-types": "^15.7.2",
    "react": "^16.13.1",
    "react-alice-carousel": "^1.19.3",
    "react-dom": "^16.13.1",
    "react-helmet": "^5.2.1",
    "shopify-buy": "^2.11.0",
    "styled-components": "^4.4.1"
  },
  "devDependencies": {
    "babel-plugin-styled-components": "^1.10.7",
    "gatsby-plugin-styled-components": "^3.3.10"
  },`

I refactored this by referencing AlexanderProd's build. @alexislepresle you could also consider importing [specific modules](https://bulma.io/documentation/overview/modular/) from Bulma, rather then importing the entire library which adds bloat.

**Comment by alexislepresle** [comment]
Hello everyone, 

By making a few changes and updating Gatsby, I managed to go from 30 -> 72 in performance. I will continue to look at how I can get as close to 100 as possible :) 

<img width="593" alt="Screenshot 2020-07-30 at 10 14 42" src="https://user-images.githubusercontent.com/33030155/88898756-7d04c200-d24d-11ea-982c-58e09dd94864.png">

**Comment by Chizzah** [comment]
Amazing work Alexis. I tried for a week or more and could not get similar results. Very good dev work!

**Comment by alexislepresle** [comment]
<img width="555" alt="Screenshot 2021-01-10 at 11 38 04" src="https://user-images.githubusercontent.com/33030155/104120601-4e306300-5338-11eb-8eb1-20a239b26cd2.png">

The performance is awesome 🎉🎉
