### ISSUE TITLE
Fetch API cannot load

### ISSUE THREAD

**Issue by pmarxbraun** [alexislepresle/gatsby-shopify-theme#5]
Hi @alexislepresle , 
I got this error on the homepage with my dev store credentials. 

`Fetch API cannot load webpack-internal:///./src/components/ProductList/productBox.js. URL scheme must be "http" or "https" for CORS request.`

Do you what is causing this ? 
Thanks

**Comment by pmarxbraun** [comment]
it happens when Images array is empty

**Comment by alexislepresle** [comment]
Hi @pmarxbraun, I see that you have managed to find the solution to your problem :)
